[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "simple-image-hosting"
version = "0.1.2"
description = "Simple image hosting"
readme = "README.md"
requires-python = ">=3.10"
license = { text = "Apache 2.0" }
authors = [
  { name = "pkufool" }
]
dependencies = [
  "fastapi>=0.115.0",
  "uvicorn>=0.30.6",
  "python-multipart>=0.0.12",
  "python-dotenv>=1.0.1",
  "sqlalchemy>=2.0.35",
  "Pillow>=11.1.0",
  "pillow-heif>=0.21.0",
  "PyMySQL>=1.1.1"
]

[project.scripts]
simple-image = "simple_image.cli:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
include = ["simple_image*"]

[tool.setuptools.package-data]
simple_image = ["web/**/*"]